<form action="/courses" method="post">
    <div>
        <label>
            Имя
            <input type="text" name="course[title]">
        </label>
        <?php if(isset($errors['title'])): ?>
        <div><?= $errors['title'] ?></div>
        <?php endif; ?>
    </div>
    <div>
        <lavel>
            Тип курса
            <select name="course[paid]">
                <option <?= isset($course['paid']) && $course['paid'] ? 'selected' : '' ?> value="1">Платный</option>
                <option <?= isset($course['paid']) && $course['paid'] ? 'selected' : '' ?> value="free">Бесплатный</option>
            </select>
        </lavel>
        <?php if (isset($errors['paid'])): ?>
        <div><?= $errors['paid'] ?></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="New">
</form>
