<a href="/">Main</a><br>
<a href="/users/new">New user</a>
<form action="/users" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term)?>"/>
    <input type="submit" value="Search" />
</form>
<?php require_once __DIR__ . DIRECTORY_SEPARATOR .'flashes.php' ?>
<?php foreach ($users as $user): ?>
<div>
    <a href="/users/<?= htmlspecialchars($user['id']) ?>">
        <?= htmlspecialchars($user['name']) . " " . htmlspecialchars($user['email']) ?>
</div>
<?php endforeach ?>

