<a href="/users">Пользователи</a>
<?php foreach ($userInfo as $key => $value): ?>
<div>
    <?="{$key}: {$value}"?>
</div>
<?php endforeach ?>
<a href="/users/<?= htmlspecialchars($userInfo['id']) ?>/edit">edit</a>
<form action="/users/<?= htmlspecialchars($userInfo['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Remove">
</form>
<?php require_once __DIR__ . DIRECTORY_SEPARATOR .'flashes.php' ?>